### ISSUE TITLE
Excepcion en filtros 

### ISSUE THREAD

**Issue by jthmiranda** [bolpros/negociacion#6]
Se lanza un __javax.ejb.EJBException__ desde que me he conectado a la *vpn* sin realizar ningun proceso mas que logearme dentro del aplicativo

Primer salida
```
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-6044] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.QueryException
Exception Description: The primary key read from the row [ArrayRecord(
	FILTROS.NAME => null)] during the execution of the query was detected to be null.  Primary keys must not contain null.
Query: ReadAllQuery(name="Items" referenceClass=Filtros sql="SELECT DISTINCT CORRELATIVO NAME FROM V_NEGOCIACION where id_estado=? ORDER BY 1")
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:480)
	at com.bolpros.ejb.NegociacionFacade.Items(NegociacionFacade.java:117)
```

Segunda salida
```
Caused by: Exception [EclipseLink-6044] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.QueryException
Exception Description: The primary key read from the row [ArrayRecord(
	FILTROS.NAME => null)] during the execution of the query was detected to be null.  Primary keys must not contain null.
Query: ReadAllQuery(name="Items" referenceClass=Filtros sql="SELECT DISTINCT CORRELATIVO NAME FROM V_NEGOCIACION where id_estado=? ORDER BY 1")
	at org.eclipse.persistence.exceptions.QueryException.nullPrimaryKeyInBuildingObject(QueryException.java:922)
```

**Comment by jthmiranda** [comment]
Solventado! se le colocó un ``` @ID ``` al atributo correlativo de la entidad
